# Application Name
spring.application.name=testcontainers-with-spring-boot-redis

# Redis Default Configuration (will be overridden by Testcontainers in tests)
spring.data.redis.host=localhost
spring.data.redis.port=6379


# Suppress Lettuce connection warnings during shutdown
logging.level.io.lettuce.core.protocol.ConnectionWatchdog=ERROR
